module.exports = {
    Repository: require('./src/repository'),
    Scope: require('./src/utils/scope'),
    Position: require('./src/utils/position'),
    Comment: require('./src/utils/comment'),
    Options: require('./src/repository/options'),
    Node: require('./src/data/node'),
    Block: require('./src/nodes/block'),
    Class: require('./src/nodes/class'),
    Constant: require('./src/nodes/constant'),
    Declare: require('./src/nodes/declare'),
    Define: require('./src/nodes/define'),
    Expr: require('./src/nodes/expr'),
    External: require('./src/nodes/external'),
    File: require('./src/nodes/file'),
    Function: require('./src/nodes/function'),
    Interface: require('./src/nodes/interface'),
    Method: require('./src/nodes/method'),
    Namespace: require('./src/nodes/namespace'),
    Property: require('./src/nodes/property'),
    Trait: require('./src/nodes/trait'),
    Usegroup: require('./src/nodes/usegroup'),
    Variable: require('./src/nodes/variable')
};